<%@ Page Language="C#" AutoEventWireup="true" CodeFile="levels.aspx.cs" Inherits="levels" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
        <title> OnLine Exam System </title>

    <style>
        .style1 {
            width: 1024px;
        }
        .style4 {
            font-family :"Centaur";
                font-size:xx-large;
                font-weight:700;
                color:#CC3399;
                text-align:center;
                padding:0;
            background-color: #FFFFFF;
            }
       
    </style>

       
        
</head>
<body>
      <table class="style1" align="center">
            <tr>
                <td  class="style4">
                    
                 College levels & Departments</td>
            </tr>
            
            </table>

    <form id="form1" runat="server">
        &nbsp;<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" style="margin-left: 0px; margin-top: 0px;" Width="802px" Height="111px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" InsertVisible="False" />
                <asp:BoundField DataField="FirstLevel" HeaderText="FirstLevel" SortExpression="FirstLevel" />
                <asp:BoundField DataField="SecondLevel" HeaderText="SecondLevel" SortExpression="SecondLevel" />
                <asp:BoundField DataField="ThirdLevel" HeaderText="ThirdLevel" SortExpression="ThirdLevel" />
                <asp:BoundField DataField="FourthLevel" HeaderText="FourthLevel" SortExpression="FourthLevel" />
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
             ConnectionString="<%$ ConnectionStrings:projConnectionString %>"
             SelectCommand="SELECT * FROM [Level]"  
             UpdateCommand="UPDATE Level SET FirstLevel = @FirstLevel, SecondLevel = @SecondLevel, ThirdLevel = @ThirdLevel, FourthLevel = @FourthLevel WHERE (Id = @Id)"
     DeleteCommand="DELETE FROM Level WHERE (Id = @Id)"    >
        </asp:SqlDataSource>
   
        <br />
        <hr />
        <br />
        <asp:Label ID="Label1" runat="server" Text="FirstLevel"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         <asp:TextBox ID="TextBox1" runat="server" Width="183px"></asp:TextBox>
        <br />
        <br />

   <asp:Label ID="Label2" runat="server" Text="FirstLevel"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       <asp:TextBox ID="TextBox2" runat="server" Width="183px"></asp:TextBox>
        <br />
        <br />

        <asp:Label ID="Label3" runat="server" Text="FirstLevel"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <asp:TextBox ID="TextBox3" runat="server" Width="183px"></asp:TextBox>
        <br />
        <br />

         <asp:Label ID="Label4" runat="server" Text="FirstLevel"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:TextBox ID="TextBox4" runat="server" Width="183px"></asp:TextBox>
        <br />
        <br />


        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" Width="189px" BackColor="#26A69A" style="margin-left: 92px; font-weight: 700; color: #CC3399; background-color: #FFFFFF;" Height="32px" />
        <br />
    </form>
</body>
</html>
