<%@ Page Language="C#" AutoEventWireup="true" CodeFile="subjects.aspx.cs" Inherits="subjects" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
            .style4 {
            font-family :"Centaur";
                font-size:xx-large;
                font-weight:700;
                color:#CC3399;
                text-align:center;
                padding:0;
            background-color: #FFFFFF;
            }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        
      <table class="style1" align="center">
            <tr>
                <td  class="style4">
                    
                    Proffesror Subjects
                    <br />
                </td>
            </tr>
            
            </table>

    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Height="52px" Width="320px">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Proff_Name" HeaderText="Proff_Name" SortExpression="Proff_Name" />
                <asp:BoundField DataField="Proff_Subject" HeaderText="Proff_Subject" SortExpression="Proff_Subject" />
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
            
        </asp:GridView>
        <br />
        <hr />
        
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource2" Width="319px">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Proff_Name" HeaderText="Proff_Name" SortExpression="Proff_Name" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:projConnectionString %>" SelectCommand="SELECT * FROM [Register]"></asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
             ConnectionString="<%$ ConnectionStrings:projConnectionString %>" SelectCommand="SELECT * FROM [Subject]"
             UpdateCommand="UPDATE Subject SET Proff_Name = @Proff_Name, Proff_Subject = @Proff_Subject WHERE (Id = @Id)"
             DeleteCommand="DELETE FROM Subject WHERE (Id = @Id)" 
  
            
            
            ></asp:SqlDataSource>
         <br />
        <hr />
        <br />
        <asp:Label ID="Label1" runat="server" Text="Proffesor Name"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         <asp:TextBox ID="TextBox6" runat="server" Width="179px"></asp:TextBox>
        <br />
        <br />

   <asp:Label ID="Label2" runat="server" Text="Proffesor Subject Name"></asp:Label>         &nbsp;&nbsp;&nbsp;&nbsp; <asp:TextBox ID="TextBox7" runat="server" Width="179px" style="margin-left: 13px"></asp:TextBox>
        <br />
          <br />


        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" Width="87px" BackColor="#26A69A" style="margin-left: 77px; color: #CC3399; font-weight: 700; background-color: #FFFFFF;" Height="32px" />
        <br /><br />
    
    </div>
    </form>
</body>
</html>
